### Loading the fmri matlab dataset to python

In [148]:
import sklearn
import numpy as np
import scipy.io as sio
from sklearn.model_selection import KFold

#### Download the dataset to data folder fetch the file names

In [149]:
filename = 'data/data-science-P1.mat'

#### Function to loading the data

In [144]:
def decodeData(filename, multi_dimention=False, category_required=False, shuffle=False):
    mat_contents = sio.loadmat(filename, squeeze_me=True)
    
    # fetching the label details
    info = mat_contents['info']
    
    category, label, epoch = [], [], []
    for item in info:
        category.append(item[0])
        label.append(item[2])
        epoch.append(item[4])

    if category_required:
        Y = np.array(category)
    else:
        Y = np.array(label)
    
    Y = Y.reshape(6, 60)
    
    # fetching the fmri data
    if not multi_dimention:
        X = mat_contents['data'].reshape(6, 60)
    else:
        # need to implement 3D convert logic
        X = mat_contents['data']
    
    return X, Y

In [145]:
X, Y = decodeData(filename)

#### Test and train split example

In [155]:
kf = KFold(n_splits=6)
for train_index, test_index in kf.split(range(6)):
    print(train_index, test_index)

[1 2 3 4 5] [0]
[0 2 3 4 5] [1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]
