In [12]:
import urllib2
import numpy
from scipy.io import loadmat
from bs4 import BeautifulSoup
import numpy as np

In [13]:
quote_page = 'http://www.cs.cmu.edu/~tom/science2008/semanticFeatureVectors.html'

In [14]:
page = urllib2.urlopen(quote_page)

In [15]:
soup = BeautifulSoup(page, 'html.parser')

In [16]:
label_data = soup.find_all('a')

labels = []
for l in label_data:
    attr = l.attrs
    if 'name' in attr and l['name'] != 'top':
        labels.append(l['name'])

In [17]:
verbs_data = soup.find_all('ul')
v = verbs_data[0]

In [18]:
vrbd = dict()
for v in verbs_data[:1]:
    vrb = v.text.split('\n')[1:-1]
    for vr in vrb:
        vrbd[vr.split()[0]] = float(0.0)
print vrbd

{u'taste': 0.0, u'move': 0.0, u'say': 0.0, u'touch': 0.0, u'fear': 0.0, u'open': 0.0, u'manipulate': 0.0, u'fill': 0.0, u'neared': 0.0, u'approach': 0.0, u'listen': 0.0, u'run': 0.0, u'see': 0.0, u'rub': 0.0, u'break': 0.0, u'lift': 0.0, u'hear': 0.0, u'wear': 0.0, u'eat': 0.0, u'smell': 0.0, u'ride': 0.0, u'drive': 0.0, u'clean': 0.0, u'enter': 0.0, u'push': 0.0}


In [19]:
vrbds = list()
for v in verbs_data:
    vrb = v.text.split('\n')[1:-1]
    for vr in vrb:
        verb_l = vr.split()[0]
        verb_p = vr.split()[-1].split(')')[0][1:]
        vrbd[verb_l] = float(verb_p)
    print vrbd
    vrbds.append(vrbd.values())
    for vr in vrb:
        vrbd[vr.split()[0]] = float(0.0)

{u'taste': 0.486, u'move': 0.054, u'say': 0.52, u'touch': 0.07, u'fear': 0.013, u'open': 0.19, u'manipulate': 0.0, u'fill': 0.031, u'neared': 0.167, u'approach': 0.041, u'listen': 0.041, u'run': 0.181, u'see': 0.52, u'rub': 0.018, u'break': 0.069, u'lift': 0.018, u'hear': 0.143, u'wear': 0.214, u'eat': 0.158, u'smell': 0.018, u'ride': 0.079, u'drive': 0.085, u'clean': 0.024, u'enter': 0.054, u'push': 0.011}
{u'taste': 0.027, u'move': 0.088, u'say': 0.592, u'touch': 0.075, u'fear': 0.041, u'open': 0.175, u'manipulate': 0.002, u'fill': 0.031, u'neared': 0.069, u'approach': 0.028, u'listen': 0.075, u'run': 0.303, u'see': 0.449, u'rub': 0.022, u'break': 0.033, u'lift': 0.041, u'hear': 0.208, u'wear': 0.048, u'eat': 0.435, u'smell': 0.163, u'ride': 0.052, u'drive': 0.053, u'clean': 0.146, u'enter': 0.068, u'push': 0.031}
{u'taste': 0.027, u'move': 0.045, u'say': 0.0, u'touch': 0.08, u'fear': 0.367, u'open': 0.056, u'manipulate': 0.0, u'fill': 0.048, u'neared': 0.115, u'approach': 0.014, u'l

In [20]:
print vrbds

[[0.486, 0.054, 0.52, 0.07, 0.013, 0.19, 0.0, 0.031, 0.167, 0.041, 0.041, 0.181, 0.52, 0.018, 0.069, 0.018, 0.143, 0.214, 0.158, 0.018, 0.079, 0.085, 0.024, 0.054, 0.011], [0.027, 0.088, 0.592, 0.075, 0.041, 0.175, 0.002, 0.031, 0.069, 0.028, 0.075, 0.303, 0.449, 0.022, 0.033, 0.041, 0.208, 0.048, 0.435, 0.163, 0.052, 0.053, 0.146, 0.068, 0.031], [0.027, 0.045, 0.0, 0.08, 0.367, 0.056, 0.0, 0.048, 0.115, 0.014, 0.023, 0.261, 0.205, 0.04, 0.027, 0.013, 0.061, 0.025, 0.421, 0.073, 0.067, 0.042, 0.039, 0.043, 0.009], [0.018, 0.079, 0.294, 0.023, 0.015, 0.105, 0.0, 0.02, 0.097, 0.031, 0.022, 0.301, 0.46, 0.004, 0.06, 0.014, 0.075, 0.049, 0.742, 0.062, 0.054, 0.042, 0.072, 0.078, 0.011], [0.005, 0.054, 0.119, 0.013, 0.023, 0.092, 0.0, 0.017, 0.053, 0.012, 0.003, 0.128, 0.123, 0.002, 0.039, 0.009, 0.03, 0.052, 0.082, 0.017, 0.961, 0.05, 0.01, 0.034, 0.012], [0.002, 0.441, 0.45, 0.206, 0.005, 0.147, 0.003, 0.026, 0.079, 0.019, 0.006, 0.103, 0.132, 0.03, 0.432, 0.548, 0.007, 0.048, 0.008, 0.00

In [21]:
X = np.array(labels)

In [23]:
y = np.array(vrbds)

In [24]:
np.save('keras/verb_labels.npy', X)

In [25]:
np.save('keras/verb_vectors.npy', y)

In [26]:
# for i in range(30):
#     print i, X[i]

for i in range(60):
    print y[i], X[i]

[0.486 0.054 0.52  0.07  0.013 0.19  0.    0.031 0.167 0.041 0.041 0.181
 0.52  0.018 0.069 0.018 0.143 0.214 0.158 0.018 0.079 0.085 0.024 0.054
 0.011] bear
[0.027 0.088 0.592 0.075 0.041 0.175 0.002 0.031 0.069 0.028 0.075 0.303
 0.449 0.022 0.033 0.041 0.208 0.048 0.435 0.163 0.052 0.053 0.146 0.068
 0.031] cat
[0.027 0.045 0.    0.08  0.367 0.056 0.    0.048 0.115 0.014 0.023 0.261
 0.205 0.04  0.027 0.013 0.061 0.025 0.421 0.073 0.067 0.042 0.039 0.043
 0.009] cow
[0.018 0.079 0.294 0.023 0.015 0.105 0.    0.02  0.097 0.031 0.022 0.301
 0.46  0.004 0.06  0.014 0.075 0.049 0.742 0.062 0.054 0.042 0.072 0.078
 0.011] dog
[0.005 0.054 0.119 0.013 0.023 0.092 0.    0.017 0.053 0.012 0.003 0.128
 0.123 0.002 0.039 0.009 0.03  0.052 0.082 0.017 0.961 0.05  0.01  0.034
 0.012] horse
[0.002 0.441 0.45  0.206 0.005 0.147 0.003 0.026 0.079 0.019 0.006 0.103
 0.132 0.03  0.432 0.548 0.007 0.048 0.008 0.001 0.01  0.071 0.021 0.024
 0.084] arm
[0.006 0.042 0.187 0.029 0.022 0.328 0.001 0.042 

In [107]:
# Loading data

data = loadmat('/Users/piyush.kumar/Documents/Archive/fMRI_project/data/data-science-P1.mat')
raw_data = []
cond_number = []
word = data['info']['word'][0]
words = list()
for i in word:
    words.append(str(i[0]))

for i in range(360):
    temp = np.array(data['data'][i][0][0])
    raw_data.append(temp)

In [108]:
verb_vs = list()
X = list(X)
for word in words:
    i = X.index(word)
    verb_vs.append(y[i])

In [109]:
verb_vs = np.array(verb_vs)
verb_vs.shape

(360, 25)

In [110]:
from sklearn import linear_model

In [111]:
X_total = np.array(raw_data)
y_total = np.array(verb_vs)

In [114]:
x = X_total

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

X_total = x

In [129]:
X_total.shape
X_total.min()

0.0

In [130]:
X_train = X_total[:300]
X_test = X_total[300:]

y_train = y_total[:300]
y_test = y_total[300:]

In [134]:
regr = list()

for i in range(25):
    regr.append(linear_model.LinearRegression())
    regr[i].fit(X_train, y_train[:, i])

In [136]:
len(regr)

25

In [132]:
test = X_train[1]

test = test.reshape(1, 21764)

In [133]:
regr.predict(X_test), y_test[:, 1]

(array([ 0.0089598 ,  0.13210741,  0.03271163,  0.08490259,  0.04193033,
         0.04816132,  0.19825593,  0.08534313,  0.02930203,  0.09518013,
         0.02278513,  0.14663281,  0.03315345,  0.10626168,  0.04605968,
         0.14634152,  0.13429848,  0.08721714,  0.07818539,  0.12552664,
         0.02384064,  0.0051026 ,  0.07114895, -0.00678449,  0.0961333 ,
         0.0632645 ,  0.09047723,  0.0102801 ,  0.12131648,  0.03038018,
         0.0453674 ,  0.14666951,  0.00879077,  0.02234592,  0.09408962,
         0.07447507,  0.0299237 ,  0.02487969,  0.06690055,  0.03214059,
         0.20839327,  0.08923267,  0.07199703,  0.15894196,  0.04573139,
         0.08919355,  0.0950562 ,  0.12551707, -0.01419266,  0.03522393,
         0.02217841,  0.08486323,  0.15468071,  0.09858008,  0.20554997,
         0.12512681,  0.11904903, -0.09101644,  0.01257059,  0.114937  ]),
 array([0.064, 0.015, 0.054, 0.012, 0.011, 0.053, 0.   , 0.047, 0.026,
        0.013, 0.088, 0.192, 0.055, 0.112, 0.044, 0

In [139]:
output = list()
for i in range(len(regr)):
    output.append(regr[i].predict(X_test))

In [141]:
output = np.array(output)

In [144]:
output

array([[-0.00803951, -0.02317235, -0.00304763, ...,  0.03193487,
         0.07999603,  0.01679515],
       [ 0.0089598 ,  0.13210741,  0.03271163, ..., -0.09101644,
         0.01257059,  0.114937  ],
       [ 0.22207812,  0.13211528,  0.20650154, ...,  0.16361468,
         0.12081666,  0.3244188 ],
       ...,
       [-0.04131353,  0.05421502, -0.02170272, ...,  0.08587525,
         0.06646109,  0.03439623],
       [ 0.04393899,  0.0081248 ,  0.07830251, ...,  0.00289018,
         0.0509843 ,  0.06874566],
       [ 0.03359146,  0.04080928, -0.01257819, ...,  0.03444911,
         0.10986459,  0.01285128]])

In [147]:
output = np.transpose(output)
output.shape, y_test.shape

((60, 25), (60, 25))

In [164]:
np.save('output.npy', output)
for i in range(60):
    print numpy.corrcoef(output[7], y_test[i])[0,1]

0.6319093733411523
0.4936360963309613
0.2738318041662416
0.5301600496269212
0.147693244485346
0.6234052712217663
0.3239186759364715
0.6956337197613529
0.45755763094614893
0.0568597546793185
0.5470653594626789
0.598340293320644
0.4257306633170009
0.4187401962397308
0.23869339612414014
0.14443926966570805
0.6330134658029678
0.08463259743669811
0.5339411272781288
0.3452464206840209
0.3403068649542352
0.5326996336280932
0.4466554658213399
0.14586705769265165
0.36439752965840144
0.0248516425234782
0.6044669218758171
0.3656545444606329
0.4834984423015309
0.29224461993886963
0.14438261563030277
0.15041404074661538
0.3993165357367309
0.3200401528480168
0.46862303312686854
-0.061617725828171155
0.4186647119839867
0.07111458444650136
0.03833588606372565
0.20334853768303715
0.008836025086717804
0.16903858871759322
0.35930132657129155
0.5758401070352906
0.5491570047323325
0.3168500085980374
0.5146251079585887
0.29784978347215907
0.6270655515092812
0.6890209893740937
0.27962667116225076
0.605212878